name: Node CI

# Push tests commits; pull_request tests PR merges
on: [ workflow_dispatch ]

defaults:
  run:
    shell: bash

jobs:
  test:
    # Setup
    runs-on: ubuntu-latest

    # Go
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Create Starter Project
        shell: bash
        run: npx "@enhance/cli@latest" new ./myproject -y

      - name: Test
        run: npm run test
